import type { Metadata } from 'next';
import { Dosis, Fasthand, Geist_Mono } from 'next/font/google';
import './globals.css';

const dosisSans = Dosis({
  variable: '--font-dosis-sans',
  subsets: ['latin'],
});

const fastHandCursive = Fasthand({
  variable: '--font-fasthand-cursive',
  weight: '400',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body
        className={`${dosisSans.variable} ${fastHandCursive.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
