import type { Metadata } from 'next';
import {
  Dosis,
  Manrope,
  Archivo,
  Fasthand,
  Geist_Mono,
} from 'next/font/google';
import './globals.css';
import { Toaster } from "@/components/ui/sonner"

const dosisSans = Dosis({
  variable: '--font-dosis-sans',
  subsets: ['latin'],
});

const manropeSans = Manrope({
  variable: '--font-manrope-sans',
});

const archivoSans = Archivo({
  variable: '--font-archivo-sans',
});

const fastHandCursive = Fasthand({
  variable: '--font-fasthand-cursive',
  weight: '400',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='dark'>
      <body
        className={`${dosisSans.variable} ${manropeSans.variable} ${archivoSans.variable} ${fastHandCursive.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
